2024-06-13_02-29-03 - INFO in video_processor.py function __init__ : Successfully loaded configuration file H:\Code_Workspace_Files\python_Workspace\pycharmwork\Software_engineering_bighomework\Config\config.json

2024-06-13_02-29-03 - INFO in video_processor.py function _load_video_sourse : Successfully loaded local video device

2024-06-13_02-29-03 - INFO in video_processor.py function _load_video_sourse : Successfully loaded network video device

2024-06-13_02-29-03 - INFO in video_processor.py function _load_video_sourse : Successfully loaded history video processor

2024-06-13_02-29-06 - ERROR in video_processor.py function load_network_video_device : Fail to load the network video device, use url is: rtsp://192.168.98.239:8554/. The url parameter is no_exist_url. Please check the url or the config file of config IP_video_device.json
NoneType: None
